# Generated by Django 5.2.1 on 2025-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='stok_minimal',
            field=models.IntegerField(default=5),
        ),
    ]
